config/routes.rb
Rails.application.routes.draw do
  root "page#index"
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
# app/controllers/projects_controller.rb

class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_path, notice: "Your project was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: "Your project was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: "Your project was successfully destroyed."
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Metify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= favicon_link_tag "icons8-clipboard-approve-64.png" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
  <div class="welcome">
    <h1>Hi Tim, Welcome to the Metify App.</h1>
  </div>

  <div class="welcome">
    <h2>Please Log in, Enter Your Project Info, and Save It!</h2>
  </div>

  <div class="welcome">
    <%= link_to "Login",
                "#",
                class: "btn btn--primary" %>
    <%= link_to "New Project",
                new_project_path,
                class: "btn btn--primary" %>
  </div>

  <div class="welcome">
    <a target="_blank" href="https://icons8.com/icon/mn2FUMgjOuKZ/clipboard-approve">
      Clipboard Approve Icon by Icons8
    </a>
  </div>

app/views/projects/_form.html.erb
<%# app/views/projects/_form.html.erb %>

<%= simple_form_for project, html: { class: "project form" } do |f| %>
  <% if project.errors.any? %>
    <div class="error-message">
      <%= project.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :name, input_html: { autofocus: true } %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/projects/_project.html.erb
<%# app/views/projects/_project.html.erb %>

<div class="project">
  <%= link_to project.name, project_path(project) %>
  <div class="project__actions">
    <%= button_to "Delete",
                  project_path(project),
                  method: :delete,
                  class: "btn btn--light" %>
    <%= link_to "Edit",
                edit_project_path(project),
                class: "btn btn--light" %>
  </div>
</div>

app/views/projects/edit.html.erb
<%# app/views/projects/edit.html.erb %>

<main class="container">
  <%= link_to sanitize("&larr; Back to Projects"), projects_path %>

  <div class="header">
    <h1>Edit Project</h1>
  </div>

  <%= render "form", project: @project %>
</main>

app/views/projects/index.html.erb
<%# app/views/projects/index.html.erb %>

<main class="container">
  <div class="header">
    <h1>Projects</h1>
    <%= link_to "New Project",
                new_project_path,
                class: "btn btn--primary" %>
  </div>

  <%= render @projects %>
</main>

app/views/projects/new.html.erb
<%# app/views/projects/new.html.erb %>

<main class="container">
  <%= link_to sanitize("&larr; Back to Projects"), projects_path %>

  <div class="header">
    <h1>New Project</h1>
  </div>

  <%= render "form", project: @project %>
</main>

app/views/projects/show.html.erb
<%# app/views/projects/show.html.erb %>

<main class="container">
  <%= link_to sanitize("&larr; Back to Projects"), projects_path %>
  <div class="header">
    <h1>
      <%= @project.name %>
    </h1>
  </div>
</main>